### ISSUE TITLE
Spanish-i10n

### ISSUE THREAD

**Issue by Josexv1** [anonimal/kovri-site.moved#14]
Hello guys, I'm working on the Spanish i10n of the site, also fixed some typos in the English one.

I will send a PR when it's fully completed.

- [x] building
- [x] es.yml
- [x] acknowledgements
- [ ] contributing
- [x] index
- [x] quality
- [x] style
- [x] faq
- [x] userguide

**Comment by anonimal** [comment]
Hi @Josexv1, can you please reopen this issue in the new repo? https://github.com/monero-project/kovri-site

Thanks again.

**Comment by anonimal** [comment]
Resolved in https://github.com/monero-project/kovri-site/pull/2. Thank you @Josexv1.
