### ISSUE TITLE
Change the link color

### ISSUE THREAD

**Issue by Josexv1** [anonimal/kovri-site.moved#15]
I think the color on links is difficult to see clearly.
![links preview](https://user-images.githubusercontent.com/12077848/27008907-ba449186-4e4d-11e7-987d-aadd69abee73.png)

**Comment by anonimal** [comment]
Hi @Josexv1, can you please reopen this issue in the new repo? https://github.com/monero-project/kovri-site

Thank you.

**Comment by anonimal** [comment]
Re-opened in https://github.com/monero-project/kovri-site/issues/3.
